search\searchBundle\Entity\SearchPalabra:
    type: entity
    table: search_palabra
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        time:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
